const list = [
  [
    "YTESTQFTACHYON",
    "HCMC",
    "RETC",
    "RNVA",
    "FDMF",
    "CBDL",
    "MNGG",
    "PRMO",
    "FTEG",
    "FCGD",
    "BRNW",
    "BDGR",
    "GBHL",
    "AZFL",
    "DSCR",
    "SPZI",
    "INCT",
    "COWI",
    "NUUU",
    "PJET",
    "KRFG",
    "ELRA",
    "PYCT",
    "MITO",
    "UBQU",
    "ECOS",
    "ECEZ",
    "NSPT",
    "PHIL",
    "HPIL",
    "AWGI",
    "ICOA",
    "WNBD",
    "SNDL",
    "BLSP",
    "FBCD",
    "EFIR",
    "GVSI",
    "AAPT",
    "GRLF",
    "HAON",
    "BRYYF",
    "TMGI",
    "SEEK",
    "PLYZ",
    "WWIO",
    "MMEX",
    "DEWM",
    "TGGI",
    "WDHR",
    "GNCP",
    "INCC",
    "FERN",
    "TBEV",
    "GARB",
    "LEDS",
    "UVSE",
    "LTNC",
    "NWGC",
    "PVDG",
    "RITE",
    "DRNK",
    "MINE",
    "EEGI",
    "SPQS",
    "IGEX",
    "SANP",
    "OCGN",
    "DRNG",
    "MDCN",
    "RDAR",
    "PRPM",
    "SAPX",
    "IHSI",
    "ERBB",
    "HVCW",
    "TONR",
    "WPMLF",
    "NECA",
    "ABEV",
    "PLTR",
    "BSRC",
    "GTEH",
    "TXTM",
    "AFOM",
    "FTXP",
    "GGII",
    "UBER",
    "ALF",
    "EEENF",
    "CTRM",
    "ATNP",
    "ICBU",
    "SVTE",
    "NIO",
    "HIPH",
    "AAPL",
    "MSPC",
    "BSSP",
    "ABWN",
  ],
	[
		"ABVG",
		"FAMI",
		"PHMB",
		"PFE",
		"USMJ",
		"WDLF",
		"NMRD",
		"APPZ",
		"VGID",
		"RGBP",
		"PLPL",
		"VIZC",
		"EWLL",
		"DGTW",
		"RTON",
		"CBYI",
		"DPLS",
		"RKT",
		"FUTL",
		"AABB",
		"GE",
		"TGRO",
		"ALKM",
		"CUBV",
		"SIML",
		"QBAN",
		"PLUG",
		"RMRK",
		"BRGO",
		"USEI",
		"RBNW",
		"NAKD",
		"NWTT",
		"PTON",
		"LFAP",
		"MRNJ",
		"VIAC",
		"MTVX",
		"AHFD",
		"VIBI",
		"IBRC",
		"GTLL",
		"RSHN",
		"SNRS",
		"AXCG",
		"MRNA",
		"NOK",
		"F",
		"SGMD",
		"RNWF",
		"ADGO",
		"TLRY",
		"APYP",
		"RMTD",
		"BOTY",
		"KYNC",
		"EWKS",
		"FNRC",
		"AMNE",
		"AMD",
		"FSLY",
		"AITX",
		"OZSC",
		"RDWD",
		"COCP",
		"GAXY",
		"ETFM",
		"ONCI",
		"MDCE",
		"WHEN",
		"MAXD",
		"ZOM",
		"WTII",
		"AMC",
		"MJWL",
		"ZNGA",
		"IFBD",
		"KGET",
		"BRTX",
		"SOS",
		"GOLD",
		"PBYA",
		"APHA",
		"SBES",
		"DNN",
		"BKMP",
		"MWWC",
		"ETEK",
		"NCLH",
		"FTWS",
		"HYSR",
		"OCLG",
		"VPER",
		"BLUU",
		"VALE",
		"RCHA",
		"TSLA",
		"EVIO",
		"BBRW",
		"THRR",
	],
	["THRR", "LEXX", "BBRW", "HL", "INND", "LKCO", "CNXS", "LCLP", "VBHI", "SMAA", "NNRX", "HBRM", "ENZC", "EXMT", "AHT", "CCL", "PUGE", "FTRCQ", "LEAS", "CIDM", "BCAP", "IMTL", "TCHH", "VXRT", "HPNN", "BLDV", "BAC", "SNMN", "GDAR", "ASKE", "SDVI", "EATR", "NOUV", "SKLZ", "TPAC", "FCEL", "FONU", "BNGO", "JPEX", "CPSL", "AFPW", "FWDG", "GDET", "LATF", "ASTI", "CLF", "PBR", "HQGE", "SRMX", "VXIT", "FCX", "ELCR", "MOSY", "CWGYF", "MCET", "AAL", "X", "IBIO", "VNTH", "PINS", "CCTR", "LUMN", "CHUC", "CSCO", "ARSN", "OPTI", "TGRR", "IRNC", "AMLH", "ESGC", "SNAP", "SHIP", "ICNM", "ICTY", "T", "SCIE", "LGBS", "VSYM", "DLCR", "JMIA", "HGLC", "CCAJ", "ITUB", "NNDM", "DKNG", "PMEA", "PRPO", "INKW", "WCVC", "PYPL", "XOM", "MCOA", "GM", "PRDL", "GGB", "VPOR", "SUTI", "NOHO", "CLWD", "MSFT"],
	["MSFT", "GRLT", "EQT", "NSAV", "ETSY", "CBDD", "DKAM", "WSGF", "RIGH", "MLHC", "MRO", "IPWG", "TME", "NGCG", "NBRI", "NKLA", "AAGC", "ITVI", "EXLA", "PVSP", "PLSB", "BRN", "ASO", "BCRX", "IDGC", "AVTI", "INTC", "CZNI", "THRA", "IDEX", "PDMI", "TWTR", "MVIS", "BIEL", "PPJE", "UXIN", "GMEV", "AMS", "XPEV", "EMBR", "TWO", "IVR", "SAFS", "CYBL", "LYFT", "ADTM", "HOME", "TRVN", "IFAN", "KGC", "AVVH", "GRSO", "RUN", "IQ", "FDFT", "SSY", "RHE", "PCT", "AUY", "ATDS", "BNTX", "C", "SABR", "MJNA", "OXY", "PTTN", "TTCM", "FB", "SMAS", "NGBL", "BLEVF", "EDU", "MARA", "DIGAF", "ARCS", "ATNX", "HTZGQ", "SENS", "GEVO", "BBD", "TXMD", "RIG", "RIOT", "LGTT", "PSLV", "BYOC", "HMNY", "LI", "SKYF", "MVES", "ITRM", "WSSE", "IPKL", "IMTV", "EHOS", "IJJP", "BP", "MYDX", "ET", "BLDP"],
	["CBTC", "UWMC", "QS", "BA", "JOB", "SLB", "CYPW", "SHMN", "SPCE", "K", "MU", "WDR", "FPVD", "FSR", "HYBE", "BANT", "FUBO", "VZ", "PMDP", "CCIV", "ATYG", "ITCJ", "NGD", "SWRM", "PTOP", "AEXE", "WKHS", "PENN", "ATOS", "EBON", "CSCW", "PTEL", "NPHC", "TNXP", "HIMX", "SQ", "AG", "VMCS", "NTRR", "MRK", "HYII", "PSRU", "KPAY", "OPEN", "CHMA", "ROOT", "CELZ", "CCTL", "XREG", "GEGP", "PCTL", "SBH", "SSTY", "SHOM", "BLRX", "FBEC", "SEGI", "DRWN", "VITX", "BNGI", "HMY", "OPMZ", "ALYI", "AMRS", "XTRM", "FHBC", "SMEV", "EUOT", "MNMD", "GSX", "BGCP", "GNUS", "UAL", "SIRI", "JMON", "LOTZ", "ORCL", "BABA", "BEHL", "GRST", "AEGY", "NWIFF", "CTLE", "PXLW", "EVFM", "INO", "AUPH", "DVN", "HFBG", "MYFT", "KALA", "ILUS", "BIEI", "HAL", "HST", "TWOH", "RCMH", "HIRU", "IFLM", "ETHE"],
	["ETHE", "JPM", "CTSH", "ADMP", "CMCSA", "KO", "HPMM", "COIN", "CS", "BTG", "CLOV", "AES", "BTX", "SPONF", "HEXO", "ISYX", "MS", "OGI", "ABNB", "CTXR", "CBBT", "GTLA", "SMVI", "GSAT", "EVTI", "PZOO", "ACST", "ASXC", "EYES", "PMCB", "IFXY", "NVAX", "BB", "RBDC", "NET", "WW", "DAL", "PBR-A", "CVS", "BBKCF", "ADT", "PCLI", "GTE", "SRNE", "ITNS", "WISH", "VPRO", "BMY", "ROKU", "EVLI", "MT", "BTSC", "TWLO", "GNGR", "PG", "MSRT", "BYRG", "HLXW", "ELTZ", "CTYX", "APA", "MUX", "BGFV", "COP", "ING", "GEGI", "VST", "TPR", "IMUN", "SAN", "NEM", "JRVR", "IAG", "SWN", "MSTF", "SNOW", "PCG", "YELL", "XFLS", "TTOO", "COG", "TIGR", "ERIC", "BIDU", "MDIN", "BKR", "DNMR", "NRZ", "DRGV", "AMRN", "NLY", "TSM", "CDEV", "QNTA", "MNVN", "TEVA", "INFY", "NYXO", "TYME", "RDFN"],
	["INFY", "RDFN", "NYXO", "KMI", "M", "CVE", "LLNW", "PAOG", "GGSM", "VTRS", "DPW", "CX", "EXK", "UEC", "RBLX", "LAC", "AA", "NVTA", "EFOI", "EESO", "GBTC", "GFI", "HMBL", "IIVI", "JAMN", "GILD", "DDOG", "BLLB", "SDC", "SESN", "SBFM", "ATVI", "VISM", "MNDP", "TELL", "LLBO", "CAN", "BPSR", "ADXS", "AVYA", "RLFTF", "ICBT", "BE", "TECK", "Z", "DIS", "JD", "ADHC", "RDS-A", "IBM", "NEOM", "CVX", "CAH", "ZHUD", "FUTS", "MFC", "ENCS", "EBAY", "SSET", "JBLU", "GYOG", "TLSS", "SLLN", "PGIE", "MGNI", "AMAT", "NUAN", "AR", "U", "FTCH", "AMT", "MO", "NAK", "IPSI", "GIS", "W", "MGLG", "ORGS", "TMUS", "CIVX", "GNW", "AZN", "AHCO", "DLAD", "INTK", "WRFX", "APPS", "HPE", "MSTO", "KATX", "COMM", "BTU", "SFOR", "DCAC", "STWC", "PPL", "FITX", "VUZI", "SYN", "WOGI"],
	["FSM", "BXRX", "EMLL", "KOS", "EMED", "PSFE", "PDXP", "WNWG", "EXPH", "FUTU", "INSG", "CARR", "CDE", "ASRT", "LMFA", "BCS", "GLUU", "HBI", "CCJ", "AU", "RIDE", "ACB", "PURA", "LU", "ADMA", "SNPW", "VYNE", "QCOM", "RNSFF", "PDPR", "HBAN", "HMPQ", "ALFIW", "PSTG", "IDCN", "RDS-B", "CATV", "INPX", "RLLCF", "BRFS", "TGB", "BLDR", "OGEN", "MOS", "MDLZ", "DOCU", "AXXA", "DKSC", "TAL", "NEE", "METX", "MFST", "ONTX", "PSYC", "CFGX", "PIHN", "RCL", "EHYD", "BSX", "PAAS", "SOAN", "SYF", "KOPN", "NKE", "STRH", "VSPC", "BRNE", "AMZN", "TRCH", "XSPT", "VGLS", "AGNC", "VDRM", "ADI", "NVDA", "XXII", "CVAC", "CLNE", "CAG", "HNST", "CRM", "FOXA", "OPK", "SPRL", "MGM", "SPWR", "ABBV", "BYND", "MRVL", "HDSN", "THORF", "VSPR", "URG", "BMIN", "SFIO", "BOXS", "ENPH", "BRAV", "NYCB", "NSEO"],
	["PFPT", "RYCEY", "EXPR", "VG", "GMZP", "IGNT", "CIG", "EXPI", "RKLC", "GMSC", "AVGR", "CPG", "WDRP", "RF", "DISCA", "FOUR", "XL", "SE", "HOFV", "CEI", "FLEX", "LTHM", "IRBL", "SU", "RIO", "AFRM", "WARM", "LVS", "ABUS", "TDOC", "TSOI", "ERUC", "MEDT", "CKYS", "KEY", "CHWY", "SNRY", "ITKH", "UAA", "HPQ", "CHIT", "MVNT", "OMHE", "BMIX", "PRTY", "BFLY", "MPC", "KHC", "STLA", "CLVS", "UUUU", "BRQS", "WRHLF", "WMT", "CHPT", "PASO", "NUE", "UMC", "JCI", "MLFB", "RGLS", "FTI", "PFNO", "PM", "MP", "RGBPP", "BRK-B", "CNHI", "TOPS", "WBA", "RTPYU", "WATT", "JNJ", "COTY", "LUV", "PTAH", "DB", "DBX", "CPNG", "WMB", "SID", "CRWD", "SEEL", "IPOF", "APTY", "MGTI", "VERU", "SB", "UPS", "BUD", "FDEI", "AMWL", "V", "XSPA", "ATWT", "GPFT", "CKPT", "DOW", "SOLO", "TXHE"],
	["KR", "CNP", "HALB", "BTDG", "UBS", "BORR", "BILI", "REED", "EDR", "FIS", "INOH", "WLAN", "LMND", "EPD", "VBIV", "FITB", "EIPC", "NSPX", "SBSW", "GPL", "LESL", "PSCO", "JNPR", "BBBY", "CLNY", "PAA", "CGC", "IGPG", "ACRL", "DDD", "CGAC", "CNCM", "TRIP", "CYDY", "MTRO", "TAK", "PDD", "ENDP", "PACB", "WISA", "EKWX", "SENY", "NFLX", "RMO", "GAHC", "DKTS", "RMSL", "HESG", "UATG", "IBN", "TRX", "TBLT", "KKR", "AKBA", "GOEV", "QUOT", "ZM", "CENX", "GOTU", "NEWH", "OPTL", "INDR", "USB", "WIT", "WY", "IMJX", "BLNK", "KIWB", "RXMD", "GT", "MET", "INFN", "TS", "GRAY", "BMXC", "BFRA", "AOVTF", "SKGO", "ON", "SVM", "GB-WT", "GRGR", "ILST", "ILIM", "ORBC", "NLOK", "VSTM", "TEN", "TPTW", "CRBP", "XERS", "NOVN", "HWM", "IONS", "ADVM", "TCOM", "EAF", "AVEW", "ZH", "PEP"],
	["SNRR", "DKGR", "FAST", "ENB", "WLSI", "NERG", "MSITF", "GLW", "TJX", "ETRN", "AMCR", "CF", "WTRH", "VSTO", "VNUE", "MNKD", "PK", "KIM", "SPFR", "GWPH", "CAT", "CHS", "FHN", "MA", "SLNO", "LSRCY", "AI", "VNTN", "KKUR", "CVNA", "BIOL", "PSWW", "AFMD", "LYG", "KL", "GME", "VIPS", "KALY", "LLKKF", "AEZS", "TFC", "SBUX", "AFL", "BEKE", "CYH", "ANF", "IGEN", "FISV", "MZEIQ", "SPPI", "ABEO", "ARST", "EQH", "IMNPQ", "GLMD", "GRCU", "UPST", "SUNW", "NRG", "DASH", "IPOE", "ENG", "EXC", "NVST", "ZTO", "BTI", "SONO", "GSK", "IGPK", "SCHW", "KODK", "MLND", "MTG", "CRSP", "GSPI", "ASM", "PHYS", "EGOC", "AM", "CXW", "MFA", "ABML", "VEON", "URBF", "EMR", "NMTR", "AGGI", "EFTI", "SBLK", "IRM", "ELY", "GPRO", "CFG", "MEDH", "DGLY", "INQD", "GBR", "GS", "VOD", "MDGC"],
	["ZYNE", "WORK", "MARK", "EXPE", "SSRM", "TXN", "HEPA", "UA", "GBT", "BHC", "BK", "RIGL", "DVAX", "TAWNF", "LVVV", "EVRI", "ITP", "MXIM", "RTX", "AIG", "NWG", "CRK", "HCEI", "WPM", "MDT", "BGEM", "SNDD", "VERB", "NYMT", "ONCT", "ABT", "CZR", "CAFS", "BANI", "STWD", "WYNN", "EOG", "NI", "HITIF", "TTI", "NOV", "PAVM", "LPX", "CRON", "KLIC", "KAR", "LLY", "QTT", "KDMN", "DECN", "BDX", "SM", "DHT", "NYT", "ERII", "FDBL", "ARYC", "O", "HLF", "PVG", "HYLN", "FNMA", "CLDR", "HBM", "RRC", "RCM", "LTMAQ", "NEX", "IVZ", "AVID", "MPW", "DMTK", "ORC", "WIMI", "GPS", "ELTK", "HGV", "TRGP", "ZONX", "PRMK", "PSTV", "ERJ", "HFC", "TFZI", "SPNV", "SLNX", "DOYU", "TXG", "WDC", "ETCG", "COF", "HMLA", "PLBY", "LTHUQ", "EVUS", "DD", "ACRX", "ZTS", "HVBTF", "HD"],
	["ACRX", "ZIM", "HD", "MAC", "LAZR", "FRSX", "FE", "MITT", "ACCD", "ADBE", "SAND", "HUYA", "CNDT", "TAP", "AIKI", "ALB", "ECCI", "ASTC", "BOXL", "HES", "EARS", "QRTEA", "CTVA", "VISL", "RECAF", "WPG", "SYY", "NXPI", "PATH", "AGI", "STM", "NXE", "MOMO", "ACAD", "IMTE", "ENTI", "CDAY", "STX", "VLDR", "WNCP", "UNH", "PTEN", "SAVE", "DKMR", "ATHX", "ZAAG", "ADM", "EH", "AGC", "D", "AMPE", "AGEN", "KPTI", "HRAL", "SNWR", "BRZL", "CFX", "GDRX", "PDOS", "FECOF", "VER", "STAY", "UAMY", "BNYN", "FEYE", "MDRR", "IFUS", "SLRX", "FBP", "WU", "LOW", "STPK", "ALC", "JSHG", "VGTL", "EGO", "STEM", "NAFS", "TGTX", "AEHR", "RLX", "ARTR", "GEO", "SFIX", "ATUS", "DHC", "ARRY", "BBDA", "FLDM", "NNOX", "MYT", "CNC", "FDX", "QD", "UGP", "PBHG", "PENMF", "BEST", "USCR", "PNYTF"],
	 ["PNYTF", "CASI", "TOMDF", "MGI", "TPNI", "NVCN", "AZRX", "STON", "KGKG", "PHUN", "FSLR", "TLGT", "WOAM", "MUDS", "CLSN", "MOTS", "STNE", "DTSL", "GPXM", "FTFT", "SSOK", "COST", "AIV", "QEDN", "GERN", "GRA", "BIGC", "EURN", "SO", "FCUUF", "ENLC", "JKS", "ELAN", "KDP", "VLO", "REAL", "PSTH", "OUT", "OPTT", "ARR", "TBBK", "PTLF", "TRMB", "FMC", "TNDM", "AVTR", "FVRR", "MRIB", "INVU", "GTCH", "FLME-WT", "WTI", "APRU", "DISCK", "GRNH", "VET", "WKEY", "FTAI", "UL", "AMGN", "CUK", "NVS", "ISNS", "TFBN", "AGTC", "CYAP", "IOVA", "STLD", "MPLX", "AZUL", "EQX", "VSPRW", "AXP", "JWN", "NCAP", "VICI", "ASFX", "INUV", "CRSR", "MBT", "DM", "COUR", "SHOP", "OHI", "FANG", "UAPC", "SPLK", "NOVA", "GSV", "RNWK", "ALLY", "BBY", "WRN", "OSTK", "SJM", "SHMP", "PTN", "MLCO", "LOPE", "ATOXF"],
	["ATOXF", "CHEK", "SSYS", "PLG", "PDGO", "VTGN", "GCI", "MMNFF", "KMX", "AMBC", "MAPT", "BNNLF", "FATE", "JNSH", "EXAS", "SLM", "SBS", "ALL", "TGT", "SONN", "MTCH", "BBL", "BRX", "CIEN", "LIN", "SVAD", "GOGL", "ASAN", "NWL", "PLAN", "SPR", "ORCC", "SILV", "SUMO", "WKSP", "GLG", "TMBR", "GDDY", "SITKF", "RWLK", "CACH", "HLT", "SLGG", "MTNB", "OLN", "PERI", "TBPMF", "MCHN", "SVRA", "PLYA", "AQB", "EPZM", "CNQ", "RNG", "NEVDF", "ZIXI", "HIMR", "MPUCF", "CCO", "AUMN", "VRT", "GTBP", "ZNNMF", "CNK", "CNX", "APO", "PALAF", "MUR", "MSMY", "BEN", "HOLX", "GTHX", "LITE", "VRSK", "SRNG", "CIM", "JG", "XRAY", "AEM", "DS", "GOGO", "KAOOY", "SRUP", "BDRBF", "NTR", "HSBC", "SPH", "TD", "CHGG", "VNT", "LPI", "BILL", "AVNW", "MAXR", "LYV", "WB", "EQC", "OKE", "SCNA", "PAGP"],
	["SCNA", "PAGP", "ZBISF", "QUIK", "DFFN", "SRNGU", "OKTA", "IDRA", "VTR", "HAYW", "ATER", "CLSK", "PEAK", "CERN", "PD", "GAU", "RESN", "PHG", "CSX", "UDR", "RIBT", "MNR", "HMHC", "PUPS", "SPOT", "COOP", "WPRT", "LIGA", "PSEC", "QRVO", "MGA", "BVN", "WWR", "HRB", "REI", "AXU", "SSSS", "ENMI", "GOL", "UPWK", "GLCC", "BHP", "MREO", "KWBT", "IKTO", "AMAZ", "ARCC", "NMRK", "TBIO", "NOW", "SOL", "PULM", "CPE", "OTIS", "CHSH", "SY", "LQDT", "INVH", "BPY", "AYX", "DSX", "CBAT", "YALA", "NEPT", "CFMS", "YNDX", "EOLS", "GDS", "TLND", "RHHBY", "TTCF", "VFC", "HRL", "UNM", "SGLN", "SNVP", "GPK", "ABQQ", "ONCX", "TRKA", "APRN", "BX", "SPRV", "SEAC", "OEG", "RDN", "NWPN", "PPBV", "MEIL", "HUBS", "IPG", "INFI", "DELL", "PEI", "MBIO", "AREC", "MCK", "ARDX", "PBF", "SPG"],
	["PBF", "CLI", "VYON", "FOLD", "DISH", "APSG", "ACTL", "STOR", "BOX", "SINX", "INFO", "BONZ", "HTHT", "TCEHY", "ICPT", "CPB", "BUNM", "ETN", "AURI", "DHY", "SNY", "EW", "POWW", "CBD", "CSOC", "PLX", "POAI", "NMM", "HOTH", "AEG", "OVV", "HGEN", "ACI", "ANDI", "MCHP", "MWK", "HAZH", "DHI", "RYAM", "TRIL", "PHM", "NWSA", "ACIC", "STEV", "GPORQ", "DT", "TMO", "PPD", "GRWG", "VCBDQ", "STL", "IMGN", "OMVE", "LGHL", "FROG", "GNPX", "MICT", "G", "RTP", "DUK", "ACGL", "ASX", "MAT", "CRTO", "KMB", "PHBI", "CURI", "OMI", "TRVG", "IRWD", "UNGS", "CI", "GIL", "BBVA", "XEL", "PXD", "SGEN", "ZS", "PING", "AEI", "NMIH", "CMS", "LKNCY", "KNDI", "PUBM", "EXPC", "SRPT", "MUFG", "ABC", "FTOC", "STAF", "RAD", "NWBO", "PGR", "BTWN", "MRKR", "XGEN", "RLAY", "NLSN", "TANH"],
	["AMTX", "RLAY", "NLSN", "TANH", "EXPD", "SIRC", "WVE", "BLXX", "PHOT", "PRMW", "NBIX", "LBTYK", "ZG", "BKEN", "FLGT", "GRPS", "DXC", "ABR", "MKD", "APH", "EVK", "UNP", "URBN", "OZON", "ALTO", "CDNS", "TAIT", "SUN", "YVR", "XCRT", "TXMC", "VYNT", "FUNFF", "RSG", "CGUD", "TSN", "DE", "BRLL", "SQM", "HYT", "BAM", "FLR", "GPN", "ERF", "IPNFF", "ICLD", "NAT", "OII", "IDCBF", "MRCY", "RAIL", "NTLA", "VFF", "NMNZF", "CCI", "GFL", "SNPR", "CUBT", "EGHT", "ROST", "AVAH", "PQEFF", "TOT", "RGS", "SMFG", "OBSV", "LBTYA", "HUN", "CB", "ACN", "SAVA", "ENCC", "BLL", "EA", "SGMO", "NXTD", "PXS", "ETR", "CNGO", "IRBS", "OPGN", "ZI", "YSG", "TUEM", "MCD", "IZEA", "INMD", "USAS", "ALDX", "CRNT", "ZSAN", "KLGG", "ADAP", "TSPG", "LIZI", "EXTR", "PZZA", "SWKS", "ZNOG", "EXTN"],
	 ["EXTN", "SHLS", "TTM", "DPWW", "PRU", "GHVI", "EQNR", "TMX", "CERS", "BQSSF", "YY", "SFM", "BKESF", "APPN", "GALT", "PFGC", "IPOF-WT", "PLYN", "BLMN", "LCTX", "GWTI", "PIXY", "FORW", "AMX", "FL", "ESTC", "VTVT", "BFARF", "LNTH", "GLOP", "RWT", "THBR", "COFPL", "MOGO", "VRAY", "PIRS", "PSX", "CWH", "DRH", "TWST", "FUNN", "MMM", "INTZ", "NTAP", "USFD", "FLWS", "COUP", "HESV", "QFIN", "TBSAU", "SI", "REKR", "GOOS", "AERI", "GSMGW", "BXMT", "XM", "ESI", "CARA", "GORO", "VLY", "REGN", "BKI", "ARNI", "CMGO", "LSPD", "BAX", "AXTA", "JAN", "RLGY", "MMP", "AQMS", "NAVI", "GH", "PSCR", "DXF", "SELB", "FWAA", "NBEV", "GSS", "UFS", "PRQR", "SIMO", "AEP", "BDR", "HOL", "NGA", "ALKS", "IP", "WFTLF", "FRO", "MYSZ", "BEAM", "IDVV", "LODE", "ABB", "SATS", "ED", "KSS", "AKAM"],
	 ["MAR", "GMNI", "VPGLF", "OUST", "ANTM", "PFWIQ", "FRT", "TSP", "QTMM", "GBOX", "PEG", "ICE", "NEO", "CAR", "HDB", "TWI", "ESSE", "SPRT", "AEVA", "SEE", "RSI", "MDRX", "APTV", "VGLDF", "EVGN", "PRSP", "HEAR", "PDSB", "HON", "PODD", "PAYA", "NBR-PA", "NOG", "TMDI", "EXEL", "ASMB", "VYGG", "PLAY", "DVLP", "TEF", "RMTI", "OGE", "ALT", "CLBS", "GNOG", "TTD", "GGTTF", "PTBTQ", "EADSY", "SCCO", "CHNG", "ULGX", "TUP", "LYB", "APLE", "COWN", "EMAN", "WM", "MDMP", "UMPQ", "DQ", "BNS", "CASG", "NOKBF", "PRNAF", "PGOG", "PGPM", "LKOLF", "RELM", "PIPI", "SHO", "APPH", "THCB", "RVLV", "HLOGF", "LNC", "INCY", "SUPV", "EL", "VIRT", "AERS", "NEP", "CCTC", "SURF", "FBIO", "PRTS", "DHR", "MUDSW", "MYHI", "MXSG", "CD", "IGT", "DOC", "AGRX", "BIGG", "BGS", "BMGP", "TRT", "DSUS", "DAC"]
	["BMGP", "HCC", "GRTS", "DSUS", "YQ", "DAC", "CDLX", "SYRS", "HLX", "GTXO", "LC", "SWBI", "AURT", "MELI", "QSR", "EB", "TEAM", "DMGGF", "SLCA", "CHX", "TWOU", "LXP", "PTE", "VIR", "HCANF", "ZGNX", "USWS", "GRNQ", "NTRA", "IO", "ARBKF", "SKX", "LSCC", "BBI", "ADBN", "PROM", "FRTD", "HOG", "TMHC", "VSBGF", "ZENG", "TDC", "MX", "UNDR", "CLNC", "SBRA", "MDMN", "CPSH", "AUNFF", "RPRX", "ALGT", "BWA", "EDIT", "EPC", "GXXM", "DNB", "BTRYF", "APXT", "XEC", "NCNO", "IGC", "CCRN", "RCII", "PRVB", "HMPT", "CELH", "CMLF", "VNTR", "AEO", "GOLF", "WRK", "PAGS", "OCSL", "NDRA", "DWIN", "FNKO", "PCAR", "SEAH", "CLIS", "PNC", "VMW", "WPF", "AVLR", "VSH", "TXT", "SHLX", "AVGO", "LEG", "ORAN", "SFTW", "ALKN", "SAIL", "WINT", "GLBS", "SFT", "HLLPF", "CTIC", "MTDR", "HZNP", "BLUE"],


];
module.exports = list;
